# Generated by Django 3.1.6 on 2021-02-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='images',
            field=models.ManyToManyField(related_name='rel_img', to='main.Images', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_cat', to='main.categories', verbose_name='Категория фотографии'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
