# Generated by Django 3.1.6 on 2021-02-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210204_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(upload_to='', verbose_name='Большое изображение'),
        ),
    ]
