# Generated by Django 3.1.6 on 2021-02-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210204_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Большое изображение'),
        ),
    ]
