# Generated by Django 3.1.6 on 2021-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210204_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Большое изображение'),
        ),
    ]
