# Generated by Django 3.1.6 on 2021-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210204_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(upload_to='big_image/', verbose_name='Большое изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Это поле не обязательное', null=True, upload_to='small_image/', verbose_name='Маленькое изображение'),
        ),
    ]
