# Generated by Django 3.1.6 on 2021-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210209_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(upload_to='big_images/', verbose_name='Большое изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Это поле не обязательное', null=True, upload_to='<django.db.models.fields.related.ForeignKey>/small_images/', verbose_name='Маленькое изображение'),
        ),
    ]
