# Generated by Django 3.1.6 on 2021-02-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210209_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(height_field=200, upload_to='big_images/', verbose_name='Большое изображение', width_field=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Это поле не обязательное', null=True, upload_to='small_images/', verbose_name='Маленькое изображение'),
        ),
    ]
