# Generated by Django 3.1.6 on 2021-02-09 13:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210209_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Это поле не обязательное', null=True, upload_to=main.models.user_directory_path, verbose_name='Маленькое изображение'),
        ),
    ]
